### PR TITLE
Add OIDC permissions

### PR DESCRIPTION
**Pull request by njuettner**
https://github.com/giantswarm/roadmap/issues/114

### CODE REVIEW

**Comment by calvix** [comment]
please also add `s3:PutObjectAcl` which is necessary for uploading public obejects

**Comment by njuettner** [comment]
I just saw below we have
```
        {
            "Effect": "Allow",
            "Action": [
                "s3:CreateBucket",
                "s3:DeleteBucket",
                "s3:DeleteObject",
                "s3:GetBucketLogging",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:PutBucketAcl",
                "s3:PutBucketEncryption",
                "s3:PutBucketLogging",
                "s3:PutBucketLifecycle",
                "s3:PutBucketTagging",
                "s3:PutObject",
                "s3:PutBucketPolicy",
                "s3:PutBucketPublicAccessBlock",
                "s3:PutEncryptionConfiguration",
                "s3:PutLifecycleConfiguration"
            ],
            "Resource": "arn:aws:s3:::*-g8s-*"
        },
```

@calvix would this cover it?

**Comment by calvix** [comment]
no

**Comment by njuettner** [comment]
I just saw the wrong one 🤦🏻

**Review by calvix — APPROVED** [review]
Cool

**Pull request merged**
