### PR TITLE
Limit S3 permissions

### PR DESCRIPTION
**Pull request by njuettner**
Targeting to limit the scope of S3 permissions for `GiantSwarmAWSOperator`.

Issue: https://github.com/giantswarm/giantswarm/issues/13967
Follow-up issue: https://github.com/giantswarm/giantswarm/issues/15160

Tested it in gauss.

### CODE REVIEW

**Review by xh3b4sd — APPROVED** [review]
If this works for you I am fine with it. Just for my interest, which permissions did we now remove? As in, how much more narrow became the scope?

**Comment by njuettner** [comment]
> If this works for you I am fine with it. Just for my interest, which permissions did we now remove? As in, how much more narrow became the scope?

We limit the scope to certain buckets which only allows aws-operator to have permissions for those specific buckets (one is the config and the other bucket is access logs). We also remove the s3:* to be a bit more specific, so potential customer might not be so concerned about what we do on behalf of S3 API.

**Comment by xh3b4sd** [comment]
Limiting to specific buckets makes sense for me.

**Review by anvddriesch — APPROVED** [review]

**Comment by anvddriesch** [comment]
Just out of curiosity, is this only for tenant cluster resources?

**Comment by njuettner** [comment]
> Just out of curiosity, is this only for tenant cluster resources?

The the role with the current permissions is also in the installation account, but the aws-operator doesn't do anything with S3 in the CP, I guess only CF and Networking permissions are relevant.

**Review by calvix — APPROVED** [review]

**Review by kopiczko — APPROVED** [review]

**Pull request merged**
