### PR TITLE
Add list oidc tags

### PR DESCRIPTION
**Pull request by njuettner**
- List OIDC tags

### CODE REVIEW

**Review by whites11 — APPROVED** [review]
Do we need this everywhere? If so we have to talk with some customers to make this happen cc @paurosello

**Comment by njuettner** [comment]
Yes unfortunately we need it. We do now add tags to OIDC provider.

**Comment by whites11** [comment]
> Yes unfortunately we need it. We do now add tags to OIDC provider. We can announce it with the new AWS release 17.3.0. If customer wants to use IRSA with custom tags they need to update their policy.

What does it happen if they don't change the role and run the IRSA thing? It just doesn't work or will it page?

**Comment by njuettner** [comment]
It would be still functional, but we will see errors in the logs that we can't update any new tags. Currently there will be no pages, but this has to be happen soon once customer will use it and we drop kiam.

**Pull request merged**
