### PR TITLE
Add CP aws-operator role

### PR DESCRIPTION
**Pull request by kopiczko**
Towards https://github.com/giantswarm/giantswarm/issues/12945

### CODE REVIEW

**Comment by kopiczko** [comment]
How can I test that, e.g. on `gauss`?

**Comment by corest** [comment]
You can create new account (you need root access to aws account) and then configure organization credentials for that account

**Comment by xh3b4sd** [comment]
I am really not sure how to evaluate this. What kind of review can I provide here?

**Comment by kopiczko** [comment]
This is checked and applied on `gauss` with little tweaks. I feel confident enough to merge.

**Pull request merged**
