### PR TITLE
Allow tagging roles

### PR DESCRIPTION
**Pull request by paurosello**
Fixes https://github.com/giantswarm/giantswarm/issues/14997

### CODE REVIEW

**Comment by paurosello** [comment]
I started thinking on only adding this permission to the operator policy, but decided to add to users in case we need to fix something.

**Review by xh3b4sd — APPROVED** [review]
LGMT if ordered alphabetically. ❤️

**Review by njuettner — APPROVED** [review]
Good you added it in GS user policy as well 👍🏻 . Otherwise tagging in management cluster account may haven't worked. Don't forget to add a comment in the CHANGELOG.md.

**Comment by paurosello** [comment]
@kopiczko is there an automated way to execute this in our installations? or is this manual?

**Comment by kopiczko** [comment]
Fully manual :)

**Comment by paurosello** [comment]
ok! will check them out

**Comment by paurosello** [comment]
- [x] gauss
- [x] anteater

**Pull request merged**
