### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by paurosello**
Improve documentation

### CODE REVIEW

**Comment by calvix** [comment]
I am a little bit afraid that this could explode as it  could cause name conflict, both AWS operator roles have same name

**Comment by pipo02mix** [comment]
can we give it a try?

**Comment by paurosello** [comment]
> I am a little bit afraid that this could explode as it could cause name conflict, both AWS operator roles have same name

But should be no problem if executed on different AWS accounts right @calvix ?

**Comment by calvix** [comment]
@paurosello yeah different accounts should be fine

**Comment by pipo02mix** [comment]
yes I tested and it will not work in same account because conflict with names

**Pull request merged**
